spring:
  application:
    name: translation-service
  
  datasource:
    url: jdbc:h2:mem:translation_db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin1234
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  cache:
    type: simple
  
  sql:
    init:
      mode: never

server:
  port: 8080

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000

logging:
  level:
    com.translation: INFO
    org.springframework.security: DEBUG